# using rustfmt nightly: 
#   rustup install nightly
#   cargo +nightly fmt
newline_style = "Unix"
max_width = 100
binop_separator = "Back"
format_strings = true
indent_style = "Visual"
empty_item_single_line = false
struct_field_align_threshold = 20
enum_discrim_align_threshold = 40
hex_literal_case = "Lower"
imports_indent = "Visual"
normalize_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
